### ISSUE TITLE
The solutions to some Quera problems in C#

### ISSUE THREAD

**Issue by HamidMolareza** [myp79/Quera-Problem-Solution#10]
Hello,
My solutions in C# language is in [this repository](https://github.com/HamidMolareza/QueraProblems).

I added [your repository](https://github.com/HamidMolareza/QueraProblems#related).

If you find it useful, please recommend it.

thank you.

**Comment by MoYousefipour** [comment]
Thank you for mention me in your repository.

**Comment by MoYousefipour** [comment]
@HamidMolareza
I add a section for contribute on Repository. If you want to see your name in Contributors in repo, you can add your solution or add your repo link in readme and request to add it.

**Comment by HamidMolareza** [comment]
Does that mean I should send a PR?

**Comment by MoYousefipour** [comment]
Yes. Exactly. you send a PR and I confirm it. So your name is shown as contributor and you mention in readme file.
